In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv('C:/Users/meetm/Desktop/adult.csv')

In [3]:
dataset.head()

age workclass  fnlwgt     education  education.num marital.status  \
0   90         ?   77053       HS-grad              9        Widowed   
1   82   Private  132870       HS-grad              9        Widowed   
2   66         ?  186061  Some-college             10        Widowed   
3   54   Private  140359       7th-8th              4       Divorced   
4   41   Private  264663  Some-college             10      Separated   

          occupation   relationship   race     sex  capital.gain  \
0                  ?  Not-in-family  White  Female             0   
1    Exec-managerial  Not-in-family  White  Female             0   
2                  ?      Unmarried  Black  Female             0   
3  Machine-op-inspct      Unmarried  White  Female             0   
4     Prof-specialty      Own-child  White  Female             0   

   capital.loss  hours.per.week native.country income  
0          4356              40  United-States  <=50K  
1          4356              18  United-States  <=50K  
2          4356              40  United-States  <=50K  
3          3900              40  United-States  <=50K  
4          3900              40  United-States  <=50K

In [4]:
dataset=dataset.replace(to_replace ="?",
                 value =np.nan)

In [5]:
dataset.head()

age workclass  fnlwgt     education  education.num marital.status  \
0   90       NaN   77053       HS-grad              9        Widowed   
1   82   Private  132870       HS-grad              9        Widowed   
2   66       NaN  186061  Some-college             10        Widowed   
3   54   Private  140359       7th-8th              4       Divorced   
4   41   Private  264663  Some-college             10      Separated   

          occupation   relationship   race     sex  capital.gain  \
0                NaN  Not-in-family  White  Female             0   
1    Exec-managerial  Not-in-family  White  Female             0   
2                NaN      Unmarried  Black  Female             0   
3  Machine-op-inspct      Unmarried  White  Female             0   
4     Prof-specialty      Own-child  White  Female             0   

   capital.loss  hours.per.week native.country income  
0          4356              40  United-States  <=50K  
1          4356              18  United-States  <=50K  
2          4356              40  United-States  <=50K  
3          3900              40  United-States  <=50K  
4          3900              40  United-States  <=50K

In [36]:
x=dataset.iloc[:,:-1].values
#by writting values at the end we will get in matrix form instead of table form

In [37]:
x

array([[90, nan, 77053, ..., 4356, 40, 'United-States'],
       [82, 'Private', 132870, ..., 4356, 18, 'United-States'],
       [66, nan, 186061, ..., 4356, 40, 'United-States'],
       ...,
       [40, 'Private', 154374, ..., 0, 40, 'United-States'],
       [58, 'Private', 151910, ..., 0, 40, 'United-States'],
       [22, 'Private', 201490, ..., 0, 20, 'United-States']], dtype=object)

In [38]:
y=dataset.iloc[:,-1].values

In [39]:
y

array(['<=50K', '<=50K', '<=50K', ..., '>50K', '<=50K', '<=50K'],
      dtype=object)

# data preprocessing

In [10]:
from sklearn.impute import SimpleImputer#it is specialy for missing values

In [11]:
imputer=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
#this above(imputer) is object we have not applied it now 

In [12]:
imputer.fit(x[:,1:])#here it's applyed(but it's not called it will not reflect the value)

SimpleImputer(strategy='most_frequent')

In [13]:
x[:,1:]=imputer.transform(x[:,1:])#so, this step will modify x 

In [14]:
x

array([[90, 'Private', 77053, ..., 4356, 40, 'United-States'],
       [82, 'Private', 132870, ..., 4356, 18, 'United-States'],
       [66, 'Private', 186061, ..., 4356, 40, 'United-States'],
       ...,
       [40, 'Private', 154374, ..., 0, 40, 'United-States'],
       [58, 'Private', 151910, ..., 0, 40, 'United-States'],
       [22, 'Private', 201490, ..., 0, 20, 'United-States']], dtype=object)

# lable encoding

In [15]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()#creation of object
le3 = LabelEncoder()
le5 = LabelEncoder()
le6 = LabelEncoder()
le7 = LabelEncoder()
le8 = LabelEncoder()
le9 = LabelEncoder()
le13 = LabelEncoder()
le=LabelEncoder()
x[:,1] = le1.fit_transform(x[:,1])#in preprocessing fit and transform can be done in one statement only
x[:,3] = le3.fit_transform(x[:,1])# as in impute we have to do it differently
x[:,5] = le5.fit_transform(x[:,1])
x[:,6] = le6.fit_transform(x[:,1])
x[:,7] = le7.fit_transform(x[:,1])
x[:,8] = le8.fit_transform(x[:,1])
x[:,9] = le9.fit_transform(x[:,1])
x[:,13] = le13.fit_transform(x[:,1])
y=le.fit_transform(y)



In [16]:
print(x)


[[90 3 77053 ... 4356 40 3]
 [82 3 132870 ... 4356 18 3]
 [66 3 186061 ... 4356 40 3]
 ...
 [40 3 154374 ... 0 40 3]
 [58 3 151910 ... 0 40 3]
 [22 3 201490 ... 0 20 3]]


In [17]:
print(y)

[0 0 0 ... 1 0 0]


# splitting dataset into training set and test set

In [18]:
from sklearn.model_selection import train_test_split# for spliting data into training and testing

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
#we are spliting data into training and testing set ,we have given 20% testing set and 80%training set

In [20]:
print(x_train)

[[41 3 208330 ... 0 51 3]
 [25 1 191921 ... 0 25 1]
 [25 3 180212 ... 0 40 3]
 ...
 [26 3 51961 ... 0 51 3]
 [44 3 115323 ... 0 40 3]
 [39 3 224531 ... 0 40 3]]


In [21]:
print(x_test)

[[56 3 274475 ... 0 40 3]
 [19 3 237455 ... 0 25 3]
 [23 3 125491 ... 0 35 3]
 ...
 [31 3 106753 ... 1740 40 3]
 [41 3 202872 ... 0 40 3]
 [37 3 161111 ... 0 40 3]]


In [22]:
print(y_train)

[0 0 0 ... 0 1 1]


In [23]:
print(y_test)

[0 0 0 ... 0 0 0]


# feature scaling( some values are to high and some are to short)

In [24]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [25]:
print(x_train)

[[ 0.17780667 -0.08668238  0.17324388 ... -0.21852035  0.85163208
  -0.08668238]
 [-0.99324468 -1.88509156  0.01823791 ... -0.21852035 -1.2548683
  -1.88509156]
 [-0.99324468 -0.08668238 -0.09236999 ... -0.21852035 -0.03957962
  -0.08668238]
 ...
 [-0.92005397 -0.08668238 -1.30388022 ... -0.21852035  0.85163208
  -0.08668238]
 [ 0.39737879 -0.08668238 -0.70533743 ... -0.21852035 -0.03957962
  -0.08668238]
 [ 0.03142525 -0.08668238  0.32628501 ... -0.21852035 -0.03957962
  -0.08668238]]


In [26]:
print(x_test)

[[ 1.28234104 -0.07964654  0.82028132 ... -0.20908231 -0.0188647
  -0.07964654]
 [-1.44850516 -0.07964654  0.46529802 ... -0.20908231 -1.23215436
  -0.07964654]
 [-1.15327855 -0.07964654 -0.60832032 ... -0.20908231 -0.42329459
  -0.07964654]
 ...
 [-0.56282532 -0.07964654 -0.78799826 ...  4.26128349 -0.0188647
  -0.07964654]
 [ 0.17524123 -0.07964654  0.13368301 ... -0.20908231 -0.0188647
  -0.07964654]
 [-0.11998539 -0.07964654 -0.26676156 ... -0.20908231 -0.0188647
  -0.07964654]]


# training dataset

In [27]:
from xgboost import XGBClassifier
model=XGBClassifier()
model.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)

# making confusion matrix(it is 2X2 matrix which summarise our model &get how much accurate our model)

In [28]:
from sklearn.metrics import confusion_matrix,accuracy_score
  #accuracy_score and confusion matrics are class
y_pred=model.predict(x_test)
cm=confusion_matrix(y_test,y_pred)#first value it will take as y true and second value as y predict
print(cm)

[[4636  330]
 [ 918  629]]


In [29]:
accuracy_score(y_test,y_pred)#accuracy prediction of model

0.8083832335329342

In [30]:
print(cm)

[[4636  330]
 [ 918  629]]


In [31]:
#here 4636 are true positive value (more than 50k)&629 (less than 50k)
#here 330 positive value are false predicted by our model same 918 false negative value  predicted by modell

In [32]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [1 0]
 [0 0]
 [0 0]]


In [33]:
#left side value in matrix is showing predicted value and right side is showing actual value

# single prediction
age=40,workclass=private,employ_inc=80000,bachelor,9,divorced,excecutive managerial,husband,white,male,0,1000,50,united-state

In [34]:
result=model.predict(sc.transform([[40, 3, 186061, 3, 10, 3, 3, 3, 3, 3, 0, 4356, 40, 3]]))
if result==[0]:
    print("person makes below $50k per year")
else:
    print("person makes above $50k per year")

person makes above $50k per year


array([[90, nan, 77053, 'HS-grad', 9, 'Widowed', nan, 'Not-in-family',
        'White', 'Female', 0, 4356, 40, 'United-States'],
       [82, 'Private', 132870, 'HS-grad', 9, 'Widowed',
        'Exec-managerial', 'Not-in-family', 'White', 'Female', 0, 4356,
        18, 'United-States']], dtype=object)